# Generated by Django 3.2.5 on 2022-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0007_customer_customer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_category',
        ),
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
