# Generated by Django 3.2.5 on 2022-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0008_auto_20220502_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('delivery_info', models.TextField()),
                ('logo', models.ImageField(upload_to='logos')),
                ('logo_tagline', models.CharField(max_length=50)),
                ('social_media', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
