# Generated by Django 3.2.5 on 2022-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0011_home_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_slider',
            name='slider_heading',
        ),
        migrations.RemoveField(
            model_name='home_slider',
            name='slider_subheading',
        ),
        migrations.AddField(
            model_name='home_slider',
            name='slider_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home_slider',
            name='slider_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home_slider',
            name='slider_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
