# Generated by Django 3.2.5 on 2022-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0012_auto_20220504_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_slider',
            name='slider_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
