# Generated by Django 3.2.5 on 2022-05-09 19:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0014_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home_slider',
            name='slider_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
