# Generated by Django 3.2.5 on 2022-05-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0015_auto_20220509_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('states', models.CharField(choices=[('gujarat', 'GUJARAT'), ('mumbai', 'MUMBAI'), ('karnataka', 'KARNATAKA')], default='gujarat', max_length=50)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('postcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
