# Generated by Django 3.2.5 on 2022-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0017_checkout_details_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_details',
            name='states',
            field=models.CharField(default='gujarat', max_length=50),
        ),
    ]
