# Generated by Django 4.0.2 on 2022-05-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0018_alter_checkout_details_states'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
