# Generated by Django 4.0.2 on 2022-05-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0019_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkout_details',
        ),
    ]
