# Generated by Django 4.0.2 on 2022-06-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0020_delete_checkout_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='social_media2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='social_media3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='social_media4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='social_media5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
