# Generated by Django 4.0.2 on 2022-06-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0021_settings_social_media2_settings_social_media3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='social_media2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='social_media3',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='social_media4',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='social_media5',
        ),
    ]
