# Generated by Django 4.0.2 on 2022-05-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0002_list_dash_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_dash_checkout_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('states', models.CharField(default='gujarat', max_length=50)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('postcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
