# Generated by Django 4.0.2 on 2022-06-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0003_list_dash_checkout_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_dash_product',
            name='list_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
