# Generated by Django 4.0.2 on 2022-06-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0004_list_dash_product_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_dash_product',
            name='list_name',
        ),
    ]
