# Generated by Django 3.2.5 on 2022-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_register',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='user_profile_images'),
        ),
    ]
