# Generated by Django 3.2.5 on 2022-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0002_website_register_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
