# Generated by Django 3.2.5 on 2022-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0003_c_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_checkout_id', models.IntegerField()),
                ('product_checkout_id', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
