# Generated by Django 4.0.2 on 2022-06-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0005_c_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('total', models.IntegerField(null=True)),
            ],
        ),
    ]
