# Generated by Django 4.0.2 on 2022-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0006_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
